name: Deploy Vite App to DigitalOcean

on:
  push:
    branches:
      - digi-dev-main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Setup pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      # Cache dependencies
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build project
      - name: Build Vite project
        run: pnpm build
        env:
          VITE_API_URL: https://dev.pitchsuite.io

      # Upload dist folder to server
      - name: 🚀 Deploy to DigitalOcean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DFTPH }}
          username: ${{ secrets.DFTPU }}
          password: ${{ secrets.DFTPP }}
          port: 22
          source: "dist/*"
          target: "/var/www/pitchsuite"

      - name: Deployment Success
        run: echo "✅ Deployment completed successfully"
