- name: 🚀 Deploy via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.DFTPH }}
    username: ${{ secrets.DFTPU }}
    password: ${{ secrets.DFTPP }}
    port: 22
    script: |
      cd /var/www/pitchsuite
      git pull origin digi-dev-main
      pnpm install
      pnpm build
